# Generated by Django 4.2.18 on 2025-01-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='population',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
