# Generated by Django 4.2.18 on 2025-01-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_job_city_alter_job_population_alter_job_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='population',
            field=models.IntegerField(),
        ),
    ]
